# Generated by Django 4.2.5 on 2023-09-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("specification", models.CharField(max_length=255)),
                ("level", models.CharField(max_length=50)),
                ("unit", models.CharField(max_length=20)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
